### ISSUE TITLE
player_collection add_item

### ISSUE THREAD

**Issue by RavenJSnow** [ajzett/Gilbo-API#3]
test_p_inv.add_itm(test_bow, 2) 

test_bow is an instance of the weapons class. Trying to add any number of them to the player inventory doesn't seem to work.

  File "C:\Users\Clara\Documents\Gilbo-API-master\Gilbo-API-master\Gilbo-API.py", line 965, in <module>
    test_p_inv.add_itm(test_bow, 2)
  File "C:\Users\Clara\Documents\Gilbo-API-master\Gilbo-API-master\Gilbo-API.py", line 618, in add_itm
    item_obtained.send(item=self.inventory())
TypeError: 'list' object is not callable

**Comment by ajzett** [comment]
I have determined the reason for the error:
Blinker requires special setup for use with the "self" argument. I have to do more research to figure out how to correctly set it up correctly, although this means that there are undoubtedly more bugs hidden in the code related to Blinker.

**Comment by ajzett** [comment]
Fixed in 0.5.5.
