### ISSUE TITLE
vendor_collection swap_item

### ISSUE THREAD

**Issue by RavenJSnow** [ajzett/Gilbo-API#5]
test_vendor.swap_item(test_bow, test_player, 1)

test_bow is an instance of the weapons class. test_player is an instance of the player class.

  File "C:\Users\Clara\Documents\Gilbo-API-master\Gilbo-API-master\Gilbo-API.py", line 971, in <module>
    test_vendor.swap_item(test_bow, test_player, 1)
AttributeError: 'vendor' object has no attribute 'swap_item'

**Comment by ajzett** [comment]
Same as #4 & #6.

**Comment by ajzett** [comment]
I have change the function "swap_itm" to "swap_item" in update 0.5.5.
