### ISSUE TITLE
item_collection rem_item & add_item

### ISSUE THREAD

**Issue by RavenJSnow** [ajzett/Gilbo-API#6]
test_p_inv.rem_item(test_potion, 1)
 
File "C:\Users\Clara\Documents\Gilbo-API-master\Gilbo-API-master\Gilbo-API.py", line 981, in <module>
    test_p_inv.rem_item(test_potion)
AttributeError: 'player_collection' object has no attribute 'rem_item'

test_p_inv.add_item(test_potion, 1)

  File "C:\Users\Clara\Documents\Gilbo-API-master\Gilbo-API-master\Gilbo-API.py", line 983, in <module>
    test_p_inv.add_item(test_potion, 1)
AttributeError: 'player_collection' object has no attribute 'add_item'

**Comment by ajzett** [comment]
Same cause as #4.

**Comment by ajzett** [comment]
The first issue is actually something that doesn't exist in the code. I'll add it, because it seems important to be able to remove items from the inventory.

**Comment by ajzett** [comment]
This is actually user error, because both functions work. The functions called in this example are misspelled.

However, I have changed the name of the functions in the 0.5.5 update to reflect the ones used here.
