### ISSUE TITLE
Battle_Manager, Magic Attack, 

### ISSUE THREAD

**Issue by RavenJSnow** [ajzett/Gilbo-API#7]
I keep getting this error whenever I try and pick an item from a list.

line 706, in __init__
    print(self.battle_dict['player'].magic_list[action2].name)
IndexError: list index out of range

**Comment by ajzett** [comment]
What type is `magic_list`?

Can you provide the initialization code for `magic_list` and `action2`?

**Comment by RavenJSnow** [comment]
action2 = int(input("What will you do?"))

class battler(vendor):
    def __init__(self, name, location, x, y, inv, coin, stats, magic_list, attack_list, heal_list, ranged_list):
@property
    def magic_list(self):
        return self.entity_dict['magic_list']

**Comment by ajzett** [comment]
There is already an implementation for linking attacks, however it is tied to weapons.

```
class weapon(equippable):
    def __init__(self, name, dscrpt, weight, val, dmg, linked_attacks=list()):
```

Each weapon has a list of attacks that it can do, and you can reuse attacks on different weapons (and those weapons will have different damage modifiers).

You can reference this list through a player's equipped list in the inventory class.
